baseURL: https://mjfreedman.com
disablePathToLower: true
languageCode: en-us
title: Michael Freedman
theme: m10c
publishDir: "./docs"
params:
  style:
    darkestColor: "#B8B8B8"
    darkColor: "#F9F9F9"
    lightColor: "#262626"
    lightestColor: "#4464AD"
    primaryColor: "#4464AD"
  avatar: "/images/avatar.jpg"
  description: "Director, Strategy at VMware Tanzu Labs"
  social:
    - icon: "github"
      name: "Github"
      url: "https://github.com/mikfreedman"
    - icon: "linkedin"
      name: "LinkedIn"
      url: "https://www.linkedin.com/in/michaelfreedman/"
