baseURL: http://mjfreedman.com
disablePathToLower: true
languageCode: en-us
title: Michael Freedman
theme: m10c
publishDir: "./docs"
params:
  avatar: "/images/avatar.jpg"
  description: "Director, VMware Tanzu"
  social:
    - icon: "github"
      name: "Github"
      url: "https://github.com/mikfreedman"
    - icon: "linkedin"
      name: "LinkedIn"
      url: "https://www.linkedin.com/in/michaelfreedman/"
